name = "pytest-test"
type = "javascript"
account_id = "d6252a570c309c113744c9e11317e271"
workers_dev = true
route = ""
zone_id = ""

kv_namespaces = [
    { binding = "THINGS", id = "06b3ff5d577d4fb29ddd8f209bed31a6", preview_id = "06b957fd6edd4b588e944f85192ff28b" }
]

[vars]
BAT = 'different'

[preview.vars]
FOO = 'bar'
SPAM = 'spam'
