name: ci

on:
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: set up python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'

    - name: install dependencies
      run: |
        pip install -U pip
        pip install -r tests/requirements.txt
        pip install -e .
        pip freeze

    - name: test
      run: |
        make test
        coverage xml
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    - uses: codecov/codecov-action@v1.0.13
      with:
        file: ./coverage.xml

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: set up python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'

    - name: install dependencies
      run: |
        pip install -U pip
        pip install -r tests/requirements-linting.txt

    - name: lint
      run: make lint

  deploy:
    needs:
      - test
      - lint
    if: "success() && startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: install
        run: |
          pip install -U pip setuptools wheel twine
          pip install -e .

      - name: set version
        run: VERSION_PATH='pytest_cloudflare_worker/version.py' python <(curl -Ls https://git.io/JT3rm)

      - name: build
        run: python setup.py sdist bdist_wheel

      - name: check
        run: twine check dist/*

      - name: upload to pypi
        run: twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.pypi_token }}
